---
- include: install.yml

- name: Load the variables
  include_vars: '{{ ansible_os_family }}.yml' 

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started

- name: Create NGINX SSL Directory 
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: create self signed SSL certificates
  command: openssl req -x509 -nodes -sha256 -days 99999 -newkey rsa:2048 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.cert -subj "/C=US/ST=NC/L=youtube/O=8gwifi/CN=zariga.com"
  args:
    creates: /etc/nginx/ssl/server.cert
  notify:
    - restart nginx

- name: Configure file permissions on certificate file.
  file:
    group: '{{ nginx_group }}'
    mode: 0600
    path: /etc/nginx/ssl/server.cert
    owner: '{{ nginx_user }}'
  notify:
    - restart nginx

- name: Configure file permissions on key file.
  file:
    group: '{{ nginx_group }}'
    mode: 0600
    path: /etc/nginx/ssl/server.key
    owner: '{{ nginx_user }}'
  notify:
    - restart nginx

- name: Install nginx.conf
  template:
    src: nginx.conf
    dest: '/etc/nginx/nginx.conf'
    force: True
    owner: '{{ nginx_user }}'
    group: '{{ nginx_group }}'
  notify:
    - restart nginx

- name: start nginx and configure to startup automatically
  service:
    name: '{{ nginx_init_name }}'
    state: started
    enabled: yes
