---
- name: Remove Legacy Services
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - telnet-server
    - telnet
    - rsh-server
    - rsh
    - ypserv
    - tftp
    - talk-server
    - xorg-x11-server-commo
    - dhcp
    - net-snmp
