---
- name: install the rkHunter,CheckrootKit, Clamv Antivirus version of ntpdate
  package:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - clamav
    - rkhunter
    - chkrootkit
