---
- name: Debian Family install the rkHunter,CheckrootKit, Clamv Antivirus
  package:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - clamav
    - rkhunter
    - chkrootkit
    - clamav-daemon
    - at
  when: ansible_os_family == 'Debian'

- name: El6/7 install the rkHunter,CheckrootKit, Clamv Antivirus
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - clamav
    - rkhunter
    - at
  when: ansible_os_family == 'RedHat'

# Run and Verify the Results
- name: Run Clamscan
  command: clamscan -i /tmp
  register: out
  async: 45
  poll: 0
- debug: var=out.stdout_lines

# Schedule the CLam Scan and Send EMails
- name: Run Clamv Once in a Week
  at:
    command: "clamscan -i /tmp | mail anish@packtpub.com"
    count: 1
    units: weeks