---
- name: install the rkHunter,CheckrootKit, Clamv Antivirus version
  package:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - clamav
    - rkhunter
    - chkrootkitchkroot
    - clamav-daemon

 - name: Run Clamv Once in a Week
   at:
    command: "clamscan -i /tmp | mail anish@packtpub.com"
    count: 1
    units: weeks