---
- include: install.yml
- include config.ssl

- name: Load the variables
  include_vars: '{{ ansible_os_family }}.yml' 

- name : Enable Mod_Rewrite
  apache2_module: name=rewrite state=present
  notify:
          - restart apache2



#- name: Install apache2.conf
#  template:
#    src: apache2.conf
#    dest: '/etc/apache2/apache2.conf'
#    force: True
#    owner: '{{ apache2_user }}'
#    group: '{{ apache2_group }}'
#  notify:
#    - restart apache2


- name: start apache2 and configure to startup automatically
  service:
    name: '{{ apache2_init_name }}'
    state: started
    enabled: yes