---
- include: install.yml
- include: configssl.yml

- name: Load the variables
  include_vars: '{{ ansible_os_family }}.yml' 

- name : Enable Mod_Rewrite
  apache2_module: name=rewrite state=present
  notify:
          - restart apache2



#- name: Install apache2.conf
#  template:
#    src: apache2.conf
#    dest: '/etc/apache2/apache2.conf'
#    force: True
#    owner: '{{ apache2_user }}'
#    group: '{{ apache2_group }}'
#  notify:
#    - restart apache2

- name: Configure Apache.
  lineinfile:
    dest: "{{ apache2_install_home }}/conf/httpd.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache2_ports_configuration }}"
  notify: restart apache2

- name: Add apache vhosts configuration.
  template:
    src: "httpd.conf"
    dest: "{{ apache_conf_path }}/{{ ansible_hostname }}.conf"
    owner: '{{ apache2_user }}'
    group: '{{ apache2_user }}'
    mode: 0644
  notify: restart apache2


- name: start apache2 and configure to startup automatically
  service:
    name: '{{ apache2_init_name }}'
    state: started
    enabled: yes