---
- name: Installing ufw APT package
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - ufw
  when: ansible_os_family == 'Debian'


- name: Installing yum firewalld package
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - firewalld
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'


- name: Installing yum firewalld package
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - iptables
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
