---
- name: Remove Legacy Services Which is not Used in the Production System
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nmap

- name: Copy the conent in the server Securely
  copy:
    content="{{ip_addr}}"
    dest=/opt/ip.txt

- name: Scan a network and find out which servers are up and running
  cron:
    name="nmap tcp report"
    minute="0"
    hour="0"
    job="nmap -v -sP -iL /opt/ip,txt > /var/log/nmap-tcp.log  2>&1"